name: GreenClouds
options:
  bundleIdPrefix: com.niritpaled
  deploymentTarget:
    iOS: "16.0"
configs:
  Debug: debug
  Release: release
targets:
  GCInstallation:
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: GCInstallation
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_NAME: "GC Installation"
        PRODUCT_BUNDLE_IDENTIFIER: com.niritpaled.GCInstallation
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: GCInstallation/Info.plist

  GCPerformance:
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: GCPerformance
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_NAME: "GC Performance"
        PRODUCT_BUNDLE_IDENTIFIER: com.niritpaled.GCPerformance
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: GCPerformance/Info.plist
